/* 
 * Defect Dojo API
 *
 * To use the API you need be authorized.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = DefectDojo.Client.SwaggerDateConverter;

namespace DefectDojo.Model
{
    /// <summary>
    /// FindingToFiles
    /// </summary>
    [DataContract]
    public partial class FindingToFiles :  IEquatable<FindingToFiles>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindingToFiles" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FindingToFiles() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FindingToFiles" /> class.
        /// </summary>
        /// <param name="findingId">findingId (required).</param>
        /// <param name="files">files (required).</param>
        public FindingToFiles(int? findingId = default(int?), List<ModelFile> files = default(List<ModelFile>))
        {
            // to ensure "findingId" is required (not null)
            if (findingId == null)
            {
                throw new InvalidDataException("findingId is a required property for FindingToFiles and cannot be null");
            }
            else
            {
                this.FindingId = findingId;
            }
            // to ensure "files" is required (not null)
            if (files == null)
            {
                throw new InvalidDataException("files is a required property for FindingToFiles and cannot be null");
            }
            else
            {
                this.Files = files;
            }
        }
        
        /// <summary>
        /// Gets or Sets FindingId
        /// </summary>
        [DataMember(Name="finding_id", EmitDefaultValue=false)]
        public int? FindingId { get; set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [DataMember(Name="files", EmitDefaultValue=false)]
        public List<ModelFile> Files { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FindingToFiles {\n");
            sb.Append("  FindingId: ").Append(FindingId).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FindingToFiles);
        }

        /// <summary>
        /// Returns true if FindingToFiles instances are equal
        /// </summary>
        /// <param name="input">Instance of FindingToFiles to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FindingToFiles input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FindingId == input.FindingId ||
                    (this.FindingId != null &&
                    this.FindingId.Equals(input.FindingId))
                ) && 
                (
                    this.Files == input.Files ||
                    this.Files != null &&
                    this.Files.SequenceEqual(input.Files)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FindingId != null)
                    hashCode = hashCode * 59 + this.FindingId.GetHashCode();
                if (this.Files != null)
                    hashCode = hashCode * 59 + this.Files.GetHashCode();
                return hashCode;
            }
        }
    }

}
