/* 
 * Defect Dojo API
 *
 * To use the API you need be authorized.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = DefectDojo.Client.SwaggerDateConverter;

namespace DefectDojo.Model
{
    /// <summary>
    /// FindingGroup
    /// </summary>
    [DataContract]
    public partial class FindingGroup :  IEquatable<FindingGroup>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindingGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FindingGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FindingGroup" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="test">test (required).</param>
        /// <param name="jiraIssue">jiraIssue.</param>
        public FindingGroup(string name = default(string), int? test = default(int?), JIRAIssue jiraIssue = default(JIRAIssue))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for FindingGroup and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "test" is required (not null)
            if (test == null)
            {
                throw new InvalidDataException("test is a required property for FindingGroup and cannot be null");
            }
            else
            {
                this.Test = test;
            }
            this.JiraIssue = jiraIssue;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Test
        /// </summary>
        [DataMember(Name="test", EmitDefaultValue=false)]
        public int? Test { get; set; }

        /// <summary>
        /// Gets or Sets JiraIssue
        /// </summary>
        [DataMember(Name="jira_issue", EmitDefaultValue=false)]
        public JIRAIssue JiraIssue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FindingGroup {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Test: ").Append(Test).Append("\n");
            sb.Append("  JiraIssue: ").Append(JiraIssue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FindingGroup);
        }

        /// <summary>
        /// Returns true if FindingGroup instances are equal
        /// </summary>
        /// <param name="input">Instance of FindingGroup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FindingGroup input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Test == input.Test ||
                    (this.Test != null &&
                    this.Test.Equals(input.Test))
                ) && 
                (
                    this.JiraIssue == input.JiraIssue ||
                    (this.JiraIssue != null &&
                    this.JiraIssue.Equals(input.JiraIssue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Test != null)
                    hashCode = hashCode * 59 + this.Test.GetHashCode();
                if (this.JiraIssue != null)
                    hashCode = hashCode * 59 + this.JiraIssue.GetHashCode();
                return hashCode;
            }
        }
    }

}
