/* 
 * Defect Dojo API
 *
 * To use the API you need be authorized.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = DefectDojo.Client.SwaggerDateConverter;

namespace DefectDojo.Model
{
    /// <summary>
    /// TestToFiles
    /// </summary>
    [DataContract]
    public partial class TestToFiles :  IEquatable<TestToFiles>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestToFiles" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestToFiles() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestToFiles" /> class.
        /// </summary>
        /// <param name="testId">testId (required).</param>
        /// <param name="files">files (required).</param>
        public TestToFiles(int? testId = default(int?), List<ModelFile> files = default(List<ModelFile>))
        {
            // to ensure "testId" is required (not null)
            if (testId == null)
            {
                throw new InvalidDataException("testId is a required property for TestToFiles and cannot be null");
            }
            else
            {
                this.TestId = testId;
            }
            // to ensure "files" is required (not null)
            if (files == null)
            {
                throw new InvalidDataException("files is a required property for TestToFiles and cannot be null");
            }
            else
            {
                this.Files = files;
            }
        }
        
        /// <summary>
        /// Gets or Sets TestId
        /// </summary>
        [DataMember(Name="test_id", EmitDefaultValue=false)]
        public int? TestId { get; set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [DataMember(Name="files", EmitDefaultValue=false)]
        public List<ModelFile> Files { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TestToFiles {\n");
            sb.Append("  TestId: ").Append(TestId).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TestToFiles);
        }

        /// <summary>
        /// Returns true if TestToFiles instances are equal
        /// </summary>
        /// <param name="input">Instance of TestToFiles to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TestToFiles input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TestId == input.TestId ||
                    (this.TestId != null &&
                    this.TestId.Equals(input.TestId))
                ) && 
                (
                    this.Files == input.Files ||
                    this.Files != null &&
                    this.Files.SequenceEqual(input.Files)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TestId != null)
                    hashCode = hashCode * 59 + this.TestId.GetHashCode();
                if (this.Files != null)
                    hashCode = hashCode * 59 + this.Files.GetHashCode();
                return hashCode;
            }
        }
    }

}
